# Generated by Django 4.2.23 on 2025-08-21 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BuyerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("industry", models.CharField(max_length=100)),
                ("locations", models.JSONField(default=list)),
                ("contact_person_name", models.CharField(max_length=100)),
                ("contact_person_position", models.CharField(max_length=100)),
                ("company_size", models.CharField(max_length=50)),
                ("machines", models.JSONField(default=list)),
                ("optional_service_requirements", models.JSONField(default=list)),
                ("qualifications_needed", models.JSONField(default=list)),
                ("safety_requirements", models.JSONField(default=list)),
                ("additional_info", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
