# Generated by Django 4.2.23 on 2025-08-21 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buyers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("machine_type", models.CharField(max_length=255)),
                ("serial_number", models.CharField(max_length=100)),
                ("locations", models.JSONField(default=list)),
                ("customer_company_name", models.CharField(max_length=255)),
                ("customer_address", models.CharField(max_length=255)),
                ("contact_person_name", models.CharField(max_length=100)),
                ("contact_person_position", models.CharField(max_length=100)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=20)),
                ("service_types", models.JSONField(default=list)),
                ("has_maintenance_history", models.BooleanField(default=False)),
                ("history_notes", models.TextField(blank=True)),
                ("issue_description", models.TextField()),
                ("technician_requirements", models.JSONField(default=list)),
                ("safety_requirements", models.JSONField(default=list)),
                ("urgency", models.CharField(max_length=20)),
                ("preferred_date", models.DateField()),
                ("alternative_dates", models.JSONField(default=list)),
                ("budget_eur", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_method", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buyers.buyerprofile",
                    ),
                ),
            ],
        ),
    ]
