# Generated by Django 4.2.23 on 2025-08-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='alternative_dates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='contact_person_position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='customer_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='locations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='safety_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='technician_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='urgency',
            field=models.CharField(max_length=50),
        ),
    ]
