# Generated by Django 4.2.23 on 2025-08-21 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("base_location", models.CharField(max_length=255)),
                ("countries", models.JSONField(default=list)),
                ("operating_regions", models.JSONField(default=list)),
                ("education", models.CharField(max_length=255)),
                ("years_experience", models.IntegerField()),
                ("certifications", models.JSONField(default=list)),
                ("tech_skills", models.JSONField(default=list)),
                ("services_offered", models.JSONField(default=list)),
                (
                    "hourly_rate_eur",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("average_rating", models.FloatField(default=0)),
                ("ratings_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
