# Generated by Django 4.2.23 on 2025-08-21 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("service_requests", "0001_initial"),
        ("providers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("file_key", models.CharField(max_length=255)),
                ("file_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=50)),
                ("size_bytes", models.IntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("access_scope", models.CharField(max_length=20)),
                (
                    "owner_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="providers.providerprofile",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="service_requests.servicerequest",
                    ),
                ),
            ],
        ),
    ]
